### ISSUE TITLE
Don't set a default value for "target_binary_version"

### ISSUE THREAD

**Issue by goetzc** [Pranit-Harekar/fastlane-plugin-codepush#3]
Having ``*`` has the default value for [`target_binary_version`](https://github.com/Pranit-Harekar/fastlane-plugin-codepush/blob/v0.2.1/lib/fastlane/plugin/codepush/actions/codepush_release_react_action.rb#L75) on `codepush_release_react_action` is dangerous, as it targets potential binary-incompatible releases. Also considering that by default the App Center CLI uses the latest version from the project's code base, the same should be done by this plugin, that would be not setting a default value.

Example:
```sh
$ npx appcenter codepush release-react -a Org/MyApp-Android -d Development

Detecting android app version:

Using the target binary version value "1.2.3" from "android/app/build.gradle".
…
```

**Comment by Pranit-Harekar** [comment]
fixed in [v0.2.2](https://rubygems.org/gems/fastlane-plugin-codepush/versions/0.2.2)
