### ISSUE TITLE
Unable to find or read "package.json" in the CWD. The "release-react" command must be executed in a React Native project folder.

### ISSUE THREAD

**Issue by spsaucier-bakkt** [Pranit-Harekar/fastlane-plugin-codepush#5]
When running:
```rb
    codepush_release_react(
      app_name: "MyOrg/myapp"
    )
```
from the `myapp/ios` (or android) directory,

I'm getting this error:
```
Error: Command 'codepush release-react -a [MyOrg]/[myapp] -t *' failed with exception "Unable to find or read "package.json" in the CWD. The "release-react" command must be executed in a React Native project folder."
```

In `myapp/package.json` I do have a [name field specified](https://github.com/microsoft/code-push/issues/629), though it doesn't exactly match the app name in App Center (surely it doesn't need to), since we are building multiple apps from the same repo for different environments.

I've tried adding `execution_dir_path: "../",` to try to run it from the project root directory, but that results in the same error.

Should this command work without specifying the execution_dir_path when called from within the `ios` or `android` folder?

**Comment by spsaucier-bakkt** [comment]
Actually, adding `execution_dir_path: "../"` did fix the issue. This is likely something most projects will encounter.

**Comment by saumyabhatnagar2000** [comment]
Where did you execution_dir_path: "../". Passing it as function param, is giving me an error
